/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GM } from "./GM";
export type { Guild } from "./Guild";
export type { GuildAction } from "./GuildAction";
export type { Piece } from "./Piece";
export type { PieceAction } from "./PieceAction";
export type { Profile } from "./Profile";
export type { Random } from "./Random";
export type { SapphireToken } from "./SapphireToken";
export type { StakingReward } from "./StakingReward";
