/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PieceAction__factory } from "./PieceAction__factory";
export { SapphireToken__factory } from "./SapphireToken__factory";
