/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20CappedUpgradeable } from "./ERC20CappedUpgradeable";
export type { IERC20MetadataUpgradeable } from "./IERC20MetadataUpgradeable";
