/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGuild } from "./IGuild";
export type { IPiece } from "./IPiece";
export type { IProfile } from "./IProfile";
