/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProfile,
  IProfileInterface,
} from "../../../contracts/interfaces/IProfile";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "profileExist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "profileId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IProfile__factory {
  static readonly abi = _abi;
  static createInterface(): IProfileInterface {
    return new utils.Interface(_abi) as IProfileInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProfile {
    return new Contract(address, _abi, signerOrProvider) as IProfile;
  }
}
