/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20CappedUpgradeable__factory } from "./ERC20CappedUpgradeable__factory";
export { IERC20MetadataUpgradeable__factory } from "./IERC20MetadataUpgradeable__factory";
